### PR TITLE
Initial commit.

### PR DESCRIPTION
**Pull request by vmihailenco**
Example:

``` php
<?php
spl_autoload_register(function($className) {
  $namespace = str_replace('\\', DIRECTORY_SEPARATOR, __NAMESPACE__);
  $className = str_replace('\\', DIRECTORY_SEPARATOR, $className);
  $class = 'src/' . (empty($namespace) ? '' : $namespace . DIRECTORY_SEPARATOR) . "{$className}.php";
  include_once($class);
});

function test($s) {
  throw new Exception($s);
}

function main() {
  $notifier = new Airbrake\Notifier(array(
    'projectId' => FILL ME,
    'projectKey' => 'FILL ME',
  ));
  $notifier->addFilter(function ($notice) {
    $notice['context']['environment'] = 'abc';
    return $notice;
  });

  $handler = new Airbrake\ErrorHandler($notifier);
  $handler->register();

  Airbrake\Instance::set($notifier);

  try {
    test('catched exception');
  } catch(Exception $e) {
    var_dump(Airbrake\Instance::notify($e));
  }

  test('uncatched exception');
}

main();
```

Todo:
- tests
- docs
- packaging

### CODE REVIEW

**Comment by joegod** [comment]
Should we leverage the errbit open-source notifier that already exists?  Sounds like it uses best-practices and is pretty slick, but might need some updating to take advantage of all possible features?
@phumpal - any other thoughts on this?

**Comment by zefer** [comment]
It may make sense to leverage that notifier. But I really like this initiative because...
- it's a good experiment/exercise in thinking about generic notifier requirements, which is really useful and will aid us in planning the Ruby gem
- it's familiarisation with php so we can make a more informed decision about the right direction
- we can always feed ideas from the errbit notifier into this one, or vice versa

**Comment by joegod** [comment]
Yup, let's just make sure we're leveraging whatever value has already been created. Improve the wheel rather than reinvent it.

**Comment by zefer** [comment]
LGTM.

As we discussed today, try to make notes about a good standard/generic API or specs for notifiers in general. This will be a _huge_ help when working with our other notifiers :smile:

**Pull request merged**
