### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by vmihailenco** [comment]
@zefer PTAL

**Comment by vinkla** [comment]
MIT is the what is specified in the `composer.json` file.

**Comment by vmihailenco** [comment]
Yeah, but it should probably be "Airbrake Technologies"... I don't know for sure.

**Comment by vinkla** [comment]
Maybe we can merge this and then you can fix it in the future?

**Comment by vmihailenco** [comment]
Works for me. Can you please fix merge conflicts?

**Comment by vinkla** [comment]
Done.

**Pull request merged**
