### PR TITLE
Use PSR-4 instead of PSR-0

### PR DESCRIPTION
**Pull request by vinkla**
Also PSR-4:d the tests and added a branch alias. Also added PHP 5.5.9 as the least required version.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Why PHP 5.5.9? Tests passed just fine on PHP 5.3.10. Can you please revert that change?

**Comment by vinkla** [comment]
PHP 5.4 will go end of life in september 2015. Big frameworks like Symfony and Laravel are already dropping PHP 5.4 support.

**Comment by vmihailenco** [comment]
Okay, but as far as I understand this PR works with PHP 5.3. So why to require higher version? I would not mind if you want to use PHP 5.5 feature, but AFAIK you don't.

**Comment by vinkla** [comment]
Fixed.

**Comment by vmihailenco** [comment]
Thanks.

**Pull request merged**
